server:
  port: 8088

spring:
    datasource:
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://google/health_data?cloudSqlInstance=healthcare-425616:europe-west2:healthcare&socketFactory=com.google.cloud.sql.postgres.SocketFactory&useSSL=false
     username: postgres
     password: YJZUt4NvSlR|4},v
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: jahonovjavohir0@gmail.com
    password: xohjjhlanadjlhjp
    properties:
      mjaail:
        smtp:
          auth: true
      mail:
        smtp:
          starttls:
            enable: true
jwt:
  secret:
    key: 753778214125442A472D4B6150645367566B59703373367639792F423F452848567890iuyiu67567886578uyutuio7865467897654678965467uior678545
  access:
    expiry: 86400000
  refresh:
    expiry: 604800000
